# -*- coding: utf-8 -*-
"""Copy of DA_Assignment_3_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iZveF6rdzHbelUbiCdIaz_CvgUme2e2M

## Exercises

Answer the questions or complete the tasks outlined in bold below, use the specific method described if applicable.

** What is 7 to the power of 4?**
"""

a=4
b=7
c=b**a
print(c)

"""** Split this string:**

    s = "Hi there Sam!"
    
**into a list. **
"""

s="Hi there Sam!"
n=s.split(" ")
print(n)

s="Hi there dad!"
n=s.split(" ")
print(n)

"""** Given the variables:**

    planet = "Earth"
    diameter = 12742

** Use .format() to print the following string: **

    The diameter of Earth is 12742 kilometers.
"""

v="The diameter of {planet} is {diameter} kilometers."
k=v.format(planet="Earth",diameter=12742)
print(k)

"""** Given this nested list, use indexing to grab the word "hello" **"""

lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

1st =[1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
print(1st[3][1][2][0])

"""** Given this nest dictionary grab the word "hello". Be prepared, this will be annoying/tricky **"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

"""** What is the main difference between a tuple and a list? **"""

t=(1,2,3)
list=[1,2,3]
tuple is immutable, and list is mutable

"""** Create a function that grabs the email website domain from a string in the form: **

    user@domain.com
    
**So for example, passing "user@domain.com" would return: domain.com**
"""

def domainGet(email):
  print(email.split('@')[-1])
email=input("please enter your email:>")
domainGet(email)

"""** Create a basic function that returns True if the word 'dog' is contained in the input string. Don't worry about edge cases like a punctuation being attached to the word dog, but do account for capitalization. **"""

def findDog(st):
  if'dog' in st.lower():
    print("True")
  else:
      print("False")
st=input("Please key a string:>")
findDog(st)

"""** Create a function that counts the number of times the word "dog" occurs in a string. Again ignore edge cases. **"""

string=input("Enter your string:")
def countdogs(string):
  count=0
  for word in string.lower().split():
    if word=='dog' or word=='dogs':
      count=count+1
      print(count)
countdogs(string)

"""### Problem
**You are driving a little too fast, and a police officer stops you. Write a function
  to return one of 3 possible results: "No ticket", "Small ticket", or "Big Ticket". 
  If your speed is 60 or less, the result is "No Ticket". If speed is between 61 
  and 80 inclusive, the result is "Small Ticket". If speed is 81 or more, the result is "Big    Ticket". Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- on your birthday, your speed can be 5 higher in all 
  cases. **
"""

print("Enter the speed(km/h)(only member phase):\n")
speed=int(input(">"))
print("Enter your birthday:(in DD/MM/YYYY format)\n")
is_birthday=str(input(">"))
def caught_speeding(speed, is_birthday):
    
    if is_birthday=='28/07/2000':
        speeding = speed - 5
    else:
        speeding = speed
    
    if speeding <=60:
        print("no ticket")
    elif speeding>61 and speeding<=80:
      print("Small Ticket")
    else:
      print("Big Ticktet")
caught_2speeding(speed,is_birthday)

"""Create an employee list with basic salary values(at least 5 values for 5 employees)  and using a for loop retreive each employee salary and calculate total salary expenditure. """

def weeklyPaid(hours_worked, wage):
    if hours_worked > 40:
        return 40 * wage + (hours_worked - 40) * wage * 1.5
    else:
        return hours_worked * wage
 
 
hours_worked = 50
wage = 100
 
pay = weeklyPaid(hours_worked, wage)
 
print(f"Total slaery expenditure: Rs.{pay:.2f} ")

"""Create two dictionaries in Python:

First one to contain fields as Empid,  Empname,  Basicpay

Second dictionary to contain fields as DeptName,  DeptId.

Combine both dictionaries. 
"""

def Merge(dict1, dict2):
    res = {**dict1, **dict2}
    return res  
# Driver code
dict1 = {'EmpName': 'rajesh','Empid':'7321', 'Basicpay': 20000}
dict2 = {'depname': 'production', 'depid': 432}
dict3 = Merge(dict1, dict2)
print(dict3)